name: build

on:
  push:
    branches:
      - 'main'
      - 'dev'
  pull_request:
    branches:
      - 'main'
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: flake8 check
        uses: py-actions/flake8@v2
        with:
          update-pip: "true"
      - name: black check
        uses: psf/black@stable
        with:
          options: "--check --verbose"
          src: "."
          use_pyproject: true
      - name: isort check
        uses: isort/isort-action@master
        with:
            requirementsFiles: "requirements.txt requirements-dev.txt"
      - name: install package
        run: |
          python -m pip install .
          
